### ISSUE TITLE
Detached camera against game rules

### ISSUE THREAD

**Issue by zacscott** [Adam-/runelite-plugins#21]
Hello there,

I think the detached camera plugin is against the game rules. It is explicitly listed as an example of what is NOT acceptable in one of the news releases:

https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1

"Offers world interaction in any detached camera mode"

**Comment by Adam-** [comment]
Hello, It doesn't offer world interaction, so I think it is okay.

**Comment by zacscott** [comment]
Marking resolved
