### ISSUE TITLE
Allow remapping of WSAD for other keyboard layouts (Detached camera)

### ISSUE THREAD

**Issue by TheZappa** [Adam-/runelite-plugins#24]
Hi,

I love your plugins. I use the detached camera one a lot, but my keyboard layout is AZERTY (french layout). Would it be possible to configure the movement keys for the camera or make it use the "key remapping" plugin?

Big thanks for taking it in consideration if possible and keep up the good work :)

Zappa

**Comment by Adam-** [comment]
The key mappings for this plugin are provided by the client as part of its oculus orb feature, so it isn't something I can change directly. It would be possible to make something remap keys for it though. The key remapping plugin doesn't have support for mapping *to* wasd, only mapping wasd to other things.

**Comment by TheZappa** [comment]
Aah okay I understand. Yeah I use key remapping to change WASD to ZQSD, because "Z" is where "W" is on French keyboard (same with "Q" and "A")

![image](https://user-images.githubusercontent.com/6859356/116764161-6c71ba00-aa20-11eb-99f4-90b3c32ce4e5.png)

**Comment by Adam-** [comment]
I also have basically no interest in doing work for users who aren't even using RuneLite, and it looks like you aren't.

**Comment by TheZappa** [comment]
Understandable, sorry to have bothered you. But do keep up the good work!

**Comment by Adam-** [comment]
Personally I find it very rude you would try to trick me into thinking you are a normal user by editing your screenshots. You are abusing my software just to cheat at a game, *and* have the gall to try and ask me to help you with that. You are everything that is wrong with the game and it really tests my patience as a maintainer having to take this type of abuse.

**Comment by TheZappa** [comment]
Yeah I understand the mistake and will not ask for any help from any dev in future. My intentions weren't to ask you to help me cheat or abuse your software, even though I made the mistake of trying to come over as a Runelite user. I just wanted to ask if it was possible to allow other key mappings for other countries, so more people would be able to use the plugin to its fullest. 

So my sincere apologies. It was not my intention to insult or even test your patience, I appreciate all the work anyone has done for Runelite and understand people that use the other clients based on runelite abuse this work (and yes I am part of the problem). So please don't let me discourage you from maintaining these projects.

**Comment by TheZappa** [comment]
Also after reading your comment and being a dev myself, I thank you for pointing it out to me this is not okay. You didn't have to reply anymore, but you did and I appreciate it.  I see this has destructive behaviour for the people who do this in their free time, I will not use that client anymore. Even though this doesn't mean anything to you. I wanted to thank you for pointing it out.
