### ISSUE TITLE
Empty essence pouch after GOTR game end

### ISSUE THREAD

**Issue by Kaaserne** [Adam-/runelite-plugins#38]
Once a game of the new Runecrafting minigame Guardians of the Rift ends, the plugin will not indicate that the pouches are empty - once a new game begins however, they will guaranteed be empty.

It also has come to my attention that if you empty the pouches while they're empty - keeping in mind that the plugin says there are pouches in it - it will not correct itself from let's say 3 -> 0, but it will keep at 3 instead.

**Comment by pwatts6060** [comment]
![image](https://user-images.githubusercontent.com/30028569/168702941-ff642bd8-7c8b-43ad-a081-6eb3d0f185f6.png)
This is the game message for when the essence is cleared in gotr from inv and pouches.

**Comment by Kaaserne** [comment]
Just leaving https://github.com/Adam-/runelite-plugins/commit/0c6e0da07c9608d497acd3f1e836d166adb64289 this and this  here https://github.com/Adam-/runelite-plugins/commit/78c77d681e146a175b380dcdbeb9353ec8ddd448
