### ISSUE TITLE
Coal bag amount update issue in BF

### ISSUE THREAD

**Issue by pauliusrug** [Adam-/runelite-plugins#49]
Hello,

Noticed this a few times, when I empty out the coal bag and it does not even show up in the inventory, the amount does not get update to zero.

I guess this happens due to there not being a game tick where on the client side the coal ever was in the inventory as it kinda went from the bag on the belt.

Thanks for a cool plugin dude (I presume)

**Comment by Adam-** [comment]
I don't think I have a plugin which does anything with the coal bag.
