### ISSUE TITLE
Support for Multiple Webhook URLs on Discord Loot Logger

### ISSUE THREAD

**Issue by sawftware** [Adam-/runelite-plugins#52]
Is it possible to get support for multiple webhook URLs? I'd like to send the loot notification to multiple servers

**Comment by Adam-** [comment]
It should already support multiple webhook urls.

**Comment by sawftware** [comment]
> It should already support multiple webhook urls.

How do I configure it? There's a single text box for the webhook url. Should I do comma separated webhook urls?

**Comment by Adam-** [comment]
It is newline separated
