### ISSUE TITLE
Feature Request: Change camera axis to use its own

### ISSUE THREAD

**Issue by andrew89898** [Adam-/runelite-plugins#87]
Hi, not sure if this is possible, been trying to look into it but haven't found anything. I'd like to be able to rotate and pan the camera around its own axis rather than some other origin, I think its usually the player. I'm familiar with other 3D cameras which allow you to do that. I think in other words I want the camera itself to be able to rotate on its on axis.

Let me know if I can clarify further or whether this is not achivable or is through other methods.

Thanks

**Comment by Adam-** [comment]
This is not possible currently. The camera positioning code is pretty baked into the client and it isn't something the plugin api surface exposes.

**Comment by andrew89898** [comment]
> This is not possible currently. The camera positioning code is pretty baked into the client and it isn't something the plugin api surface exposes.

Understood thanks for the reply, I will close the issue.
