### ISSUE TITLE
Plugin Needs Updated for New Darkmeyer Content

### ISSUE THREAD

**Issue by joe-wee** [Adam-/runelite-plugins#9]
The Darkmeyer update arrived yesterday, and added [Daeyalt Essence](https://oldschool.runescape.wiki/w/Daeyalt_essence) to the game. This new essence can be used in place of Pure essence for 50% more xp, and it can be stored in essence pouches.

Currently, filling a pouch with Daeyalt essence results in a ? icon where the number would be. Using the "check" action shows how many are inside, so I imagine the item ID for Daeyalt just needs added into the code. Unfortunately I have 0 experience with plugin development, and I'm not entirely sure how to get the item ID, but I'll work on that.

**Comment by Adam-** [comment]
added in b37a01e712a6c746a4398e02443956ed182151b6
